version: "3.8"

services:
  app:
    build: .
    container_name: recommendation_app
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    volumes:
      - .:/app       # Optional: Mount current folder for live updates
    environment:
      FLASK_ENV: production  # or "development" if you want debug
    command: >
      gunicorn -w 4 -b 0.0.0.0:8000 app:app
